#FROM tomcat:8.5.47-jdk8-openjdk
FROM tomcat:8.5.16-jre8-alpine
MAINTAINER "Suraj"
# It is just kind of documentation which tell image user that application internally runs on port 8081. It does not mean that it publishes the port
EXPOSE 8845
COPY ./target/BookServiceClient-0.0.1-SNAPSHOT.jar    book.jar
CMD ["java","-jar","book.jar"]